services:
  backend:
    build:
      context: ./src/backend
    ports:
      - "5000:5000"
    networks:
      - backend-network
    volumes:
      - ./src/backend/:/code/
    restart: "on-failure"

  frontend:
    build:
      context: ./src/frontend
    ports:
      - "3000:3000"
    networks:
      - frontend-network
      - backend-network
    volumes:
      - ./src/frontend/:/code/

  proxy:
    build:
      context: ./src/proxy
    ports:
      - "8000:80"
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - backend
      - frontend

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
